version: '3.8'

services:
  mern-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mern-app
    environment:
      - MONGO=${MONGO}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
    ports:
      - '5000:5000'  # Backend
      - '3000:3000'  # Frontend
    volumes:
      - .:/app
